Vince
UrbanCCD-UChicago/plenario-client-py pull request #13
Opened 2018-08-15 20:11 UTC by vforgione

2018-08-15 21:10 UTC, brlodi commented
Quick note, you blew away the license file in the first commit and I assume you want to put that back.

2018-08-15 21:21 UTC, vforgione commented
Closes #5 
Closes #6 
Closes #7 
Closes #8 
Closes #9

2018-08-16 15:48 UTC, sanilio requested changes
Looks great, I suggest we change `class Response` to `PlenarioResponse` to as it shadows `requests.Response`

2018-08-16 17:12 UTC, sanilio approved these changes

2018-08-16 17:13 UTC, merged